import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

import "./globals.css";
import { Toaster } from "sonner";
import Providers from "@/lib/Providers/Providers";
import Navbar from "@/components/Shared/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nft Minting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en" className={inter.className}>
        <body
          style={{
            minHeight: "100vh",
            background: "linear-gradient(90deg, #000000 0%, #111827 100%)",
            color: "white",
            margin: 0,
          }}
        >
          <AppRouterCacheProvider>
            <>
              <Toaster position="top-center" />
              <Navbar />
              {children}
            </>
          </AppRouterCacheProvider>
        </body>
      </html>
    </Providers>
  );
}
