import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import "./globals.css";
import { Toaster } from "sonner";
import { store } from "./redux/store";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PH HealthCare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>
          <>
            <Toaster position="top-center" />
            {children}
          </>
        </body>
      </html>
    </Provider>
  );
}
